version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brevly
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build: ./server
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"

  web:
    build: ./web
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  db-data:
